### ISSUE TITLE
AttributeError in `make_live_ocean_files` worker

### ISSUE THREAD

**Issue by douglatornell** [SalishSeaCast/SalishSeaNowcast#137]
After updating `numpy` in `nowcast-env` environment from 1.22.3 to 1.24.0:

```python-traceback
2022-12-22 07:26:14,218 CRITICAL [make_live_ocean_files] unhandled exception:
Traceback (most recent call last):
  File "/SalishSeaCast/NEMO_Nowcast/nemo_nowcast/worker.py", line 391, in _do_work
    checklist = self.worker_func(
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_live_ocean_files.py", line 82, in make_live_ocean_files
    filepaths = create_LiveOcean_TS_BCs(
  File "/SalishSeaCast/tools/SalishSeaTools/salishsea_tools/LiveOcean_BCs.py", line 605, in create_LiveOcean_TS_BCs
    interpl = stabilize(sigmal, interpl)
  File "/SalishSeaCast/tools/SalishSeaTools/salishsea_tools/LiveOcean_BCs.py", line 238, in stabilize
    interps['salt'][:k+1, i, j] += -add_salt/np.float(k+1)
  File "/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
```

**Comment by douglatornell** [comment]
Using aliases of builtin Python types like `np.float` was deprecated in numpy=1.20. The deprecation expired in numpy=1.24.

The exception above arises from `SalishSeaTools` (see [issue 72 there](https://github.com/SalishSeaCast/tools/issues/72)).
Searches of the `SalishSeaNowcast` codebase for `numpy.float`, `numpy.int`, their `np.` variants, etc. found no hits. So, closing this issue to work on the `SalishSeaTools` one to resolve things.
